ALTER TABLE "ModelProfile" ADD COLUMN IF NOT EXISTS "ofCutPercent" DOUBLE PRECISION NOT NULL DEFAULT 20;
ALTER TABLE "ModelInvoice" ADD COLUMN IF NOT EXISTS "ofCutPercent" DOUBLE PRECISION NOT NULL DEFAULT 20;
ALTER TABLE "ModelInvoice" ADD COLUMN IF NOT EXISTS "netAfterOF" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ModelInvoice" ADD COLUMN IF NOT EXISTS "modelSharePercent" DOUBLE PRECISION NOT NULL DEFAULT 50;
